## Spring
server:
  port: 8082

## Mongo
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: promotions

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
