## Spring
server:
  port: 8080

## Feign
feign:
  client:
    config:
      products:
        url: http://localhost:8081
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: basic
      promotions:
        url: http://localhost:8082
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: basic

## Ribbon
spring:
  cloud:
    loadbalancer:
      ribbon:
        enable: false