## Spring
server:
  port: 8080

## Feign
feign:
  client:
    config:
      products:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: basic
        url: ${PRODUCTS_API_URL:http://localhost:8081}
      promotions:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: basic
        url: ${PROMOTIONS_API_URL:http://localhost:8082}